---
title: "RadViz3D"
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, error = FALSE)
```

```{r}
library(MixSim)
library(RColorBrewer)
library(MASS)
library(freqparcoord)
library(expm)
library(grDevices)
library(radviz3d)
library(rgl)

source("modradviz2d-2.R")

viz2d_3d <- function(x, angles =  2*pi*(0:(ncol(x)-1))/ncol(x)) {
  y <- apply(X = x, MARGIN = 2, FUN = function(z)((z - min(z))/(max(z) - min(z))))
  sy <- rowSums(y)/ncol(y)
  y <- apply(X = y, MARGIN = 1, FUN = function(z)(z/sum(z)))
  y <- t(y)
  pr <- cbind(cos(angles), sin(angles))
  xproj <- cbind(y %*% pr, sy)
}

# {viz3d} function based on Artero and Oliveira's paper.
viz3d <- function(x, angles =  2*pi*(0:(ncol(x)-1))/ncol(x)) {
  y <- apply(X = x, MARGIN = 2, FUN = function(z)((z - min(z))/(max(z) - min(z))))
  #    x <- apply(X = y, MARGIN = 1, FUN = function(z)(z/sum(z)))
  #    x <- t(x)
  pr <- cbind(cos(angles), sin(angles), 1)
  xproj <- y %*% pr / ncol(y)
}

```


```{r}
sim.palette <- c("#1F78B4","#6A3D9A", "#33A02C","#E31A1C", "yellow")
set.seed(2020)
res_radviz <- list()
load("sim_data.rda")
for (i in 1:3){
  df <- sim_data[[i]]
  radialvis3d(data = df[,-1], cl = factor(df$class), domrp = F, doGtrans = F, lwd = 2, 
            alpha = 0.35, pradius = 0.02, color = sim.palette, class.labels = NULL)
  rgl::rgl.viewpoint(zoom = 0.6)
  res_radviz[[i]] <- rgl::rglwidget()
}
load("sim_data_7.rda")
for (i in 4:6){
  df <- sim_data[[i-3]]
  radialvis3d(data = df[,-1], cl = factor(df$class), domrp = F, doGtrans = F, lwd = 2, 
            alpha = 0.35, pradius = 0.02, color = sim.palette, class.labels = NULL)
  rgl::rgl.viewpoint(zoom = 0.6)
  res_radviz[[i]] <- rgl::rglwidget()
}
```


<table width="500" border="0" cellpadding="0">


<tr>
<td align="center" valign="center">
```{r}
res_radviz[[1]]
```
(i) RadViz3D, p = 4, omega = 0.001
<br />
</td>
</tr>

<tr>

<td align="center" valign="center">
```{r}
res_radviz[[2]]
```
(ii) RadViz3D, p = 4, omega = 0.01
<br />
</td>
</tr>

<tr>


<td align="center" valign="center">
```{r}
res_radviz[[3]]
```
(iii) RadViz3D, p = 4, omega = 0.05
<br />
</td>
</tr>

<tr>


<td align="center" valign="center">
```{r}
res_radviz[[4]]
```
(iv) RadViz3D, p = 7, omega = 0.001
<br />
</td>
</tr>

<tr>


<td align="center" valign="center">
```{r}
res_radviz[[5]]
```
(iv) RadViz3D, p = 7, omega = 0.01
<br />
</td>
</tr>

<tr>


<td align="center" valign="center">
```{r}
res_radviz[[6]]
```
(v) UMAP, p = 7, omega = 0.05
<br />
</td>
</tr>
</table>